import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from '@/Components/TopBar'
import Footer from "@/Components/Footer";


export const metadata = {
  title: "Practice",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='antialiased bg-[#03030c]'>
        <TopBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
