import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from '@/Components/TopBar'
import ProductPage from "@/Components/ProductPage";
import Footer from "@/Components/Footer";
import 'animate.css';
export const metadata = {
  title: "Practice",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
  
      </head>
      <body className='antialiased bg-[#03030c]'>
        <TopBar animate__fadeInUp/>
        {children}
        <ProductPage/>
        <Footer animate__fadeInUp/>
      </body>
    </html>
  );
}
